/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.7 */
/* Wed Mar 24 16:39:49 2021 */

/* parameterized module instance */
pll_clk __ (.CLKI( ), .CLKOP( ), .LOCK( ));
