/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.1 */
/* Wed Mar 24 16:40:26 2021 */

/* parameterized module instance */
aud_fifo_ip __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), 
    .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), .AlmostFull( ));
